## testparams.coffee
## THIS FILE IS AUTOMATICALLY GENERATED!! DO NOT EDIT!!
## See generate_testparams.py for modifying this file

## This file encodes the object which will be used by the model to create the sequence of availableTones used in the
## Oddball EEG paradigm to elicit a P300 response.


module.exports =
  timeout: 1500
  trialTones: ['C4', 'C4', 'C4', 'C4', 'C4', 'C4', 'C5', 'C4', 'C5', 'C4', 'C4', 'C4', 'C4', 'C4', 'C5', 'C4', 'C5', 'C4', 'C4', 'C4', 'C4', 'C5', 'C4', 'C5', 'C4', 'C4', 'C4', 'C4', 'C5', 'C4', 'C4', 'C4', 'C4', 'C5', 'C4', 'C4', 'C4', 'C4', 'C5', 'C4', 'C4', 'C5', 'C4', 'C3']
  toneLow: 'C4'
  toneHigh: 'C5'
